nelmio_api_doc:
    documentation:
        info:
            title: App Currency
            description: This is an test app!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   Bearer: [ ]
    areas: # to filter documented areas
        v1:
            path_patterns: [ ^/api/v1 ]
        default:
            path_patterns:
                - /api/doc/v1
